/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlbumItem: typeof import('./src/components/AlbumList/AlbumItem.vue')['default']
    AlbumListBody: typeof import('./src/components/AlbumList/AlbumListBody.vue')['default']
    AlbumListHeader: typeof import('./src/components/AlbumList/AlbumListHeader.vue')['default']
    AlbumListItem: typeof import('./src/components/AlbumList/AlbumListItem.vue')['default']
    AsideBar: typeof import('./src/components/MenuBar/AsideBar.vue')['default']
    ComplementStep: typeof import('./src/components/RegisterSteps/ComplementStep.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadiGroup: typeof import('element-plus/es')['ElRadiGroup']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HeaderBar: typeof import('./src/components/MenuBar/HeaderBar.vue')['default']
    ImageContainer: typeof import('./src/components/ImageControl/ImageContainer.vue')['default']
    ImageItem: typeof import('./src/components/ImageControl/ImageItem.vue')['default']
    MainHomeDiv: typeof import('./src/components/MenuBar/MainHomeDiv.vue')['default']
    MenuItemGroup: typeof import('./src/components/MenuBar/MenuItemGroup.vue')['default']
    ProfileAvatar: typeof import('./src/components/Profile/ProfileAvatar.vue')['default']
    ProfileControlPanel: typeof import('./src/components/Profile/ProfileControlPanel.vue')['default']
    ProfileDiv: typeof import('./src/components/MenuBar/ProfileDiv.vue')['default']
    ProfileEditDialog: typeof import('./src/components/Profile/ProfileEditDialog.vue')['default']
    ProfileHeader: typeof import('./src/components/Profile/ProfileHeader.vue')['default']
    ProfileInfo: typeof import('./src/components/Profile/ProfileInfo.vue')['default']
    ProfileTabs: typeof import('./src/components/Profile/ProfileTabs.vue')['default']
    RegisterStep: typeof import('./src/components/RegisterSteps/RegisterStep.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendCodeStep: typeof import('./src/components/RegisterSteps/SendCodeStep.vue')['default']
    VerifyCodeStep: typeof import('./src/components/RegisterSteps/VerifyCodeStep.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
